import asyncio
import inspect
import stat
from pathlib import Path

import pytest

from cortex.extensions.aether.cdp_agentkit import CDPSovereignWallet
from cortex.extensions.aether.redteam import RedTeamAgent
from cortex.extensions.aether.tools import AgentToolkit


def test_agent_toolkit_write_file_persists_content(tmp_path: Path) -> None:
    toolkit = AgentToolkit(tmp_path)

    result = toolkit.write_file("nested/file.py", "print('ok')\n")

    assert result == "OK — wrote 12 bytes to nested/file.py"
    assert (tmp_path / "nested" / "file.py").read_text(encoding="utf-8") == "print('ok')\n"
    source = inspect.getsource(AgentToolkit.write_file)
    assert ".write_text(" not in source


def test_agent_toolkit_write_file_rejects_escape(tmp_path: Path) -> None:
    toolkit = AgentToolkit(tmp_path)

    with pytest.raises(PermissionError):
        toolkit.write_file("../escape.txt", "blocked")


def test_agent_toolkit_direct_write_file_honors_allowed_tools(tmp_path: Path) -> None:
    toolkit = AgentToolkit(tmp_path, allowed_tools=["read_file"])

    result = toolkit.write_file("nested/file.py", "print('blocked')\n")

    assert "ToolNotAllowedError" in result
    assert not (tmp_path / "nested" / "file.py").exists()


def test_agent_toolkit_git_tools_do_not_require_bash_capability(monkeypatch, tmp_path: Path) -> None:
    toolkit = AgentToolkit(tmp_path, allowed_tools=["git"])
    captured: list[tuple[str, int]] = []

    def _fake_bash_impl(cmd: str, timeout: int) -> str:
        captured.append((cmd, timeout))
        return "M demo.py"

    monkeypatch.setattr(toolkit, "_bash_impl", _fake_bash_impl)

    result = toolkit.git_status()

    assert "M demo.py" in result
    assert captured == [("git status --short", 60)]


def test_agent_toolkit_direct_bash_honors_allowed_tools(tmp_path: Path) -> None:
    toolkit = AgentToolkit(tmp_path, allowed_tools=["git"])

    result = toolkit.bash("pwd")

    assert "ToolNotAllowedError" in result


@pytest.mark.asyncio
async def test_redteam_siege_writes_test_suite_and_inits(tmp_path: Path) -> None:
    target = tmp_path / "demo.py"
    target.write_text("def add(a, b):\n    return a + b\n", encoding="utf-8")
    toolkit = AgentToolkit(tmp_path)

    class _FakeResponse:
        content = "```python\ndef test_add():\n    assert 1 + 1 == 2\n```"

    class _FakeOrchestra:
        async def think(self, prompt, mode, system):
            return _FakeResponse()

    agent = RedTeamAgent(_FakeOrchestra())

    generated = await agent.siege("Please cover demo.py before refactor", toolkit)

    assert len(generated) == 1
    test_path = tmp_path / generated[0]
    assert test_path.exists()
    assert "def test_add()" in test_path.read_text(encoding="utf-8")
    assert (tmp_path / "tests" / "autogenerated" / "__init__.py").exists()
    assert (tmp_path / "tests" / "__init__.py").exists()


def test_cdp_wallet_write_seed_persists_file_with_0600(tmp_path: Path) -> None:
    CDPSovereignWallet._instance = None
    CDPSovereignWallet._initialized = False
    try:
        wallet = CDPSovereignWallet(seed_path=str(tmp_path / "wallet" / "seed.json"))

        wallet._write_seed("seed-data")

        seed_path = tmp_path / "wallet" / "seed.json"
        assert seed_path.read_text(encoding="utf-8") == "seed-data"
        mode = stat.S_IMODE(seed_path.stat().st_mode)
        assert mode == stat.S_IRUSR | stat.S_IWUSR
    finally:
        CDPSovereignWallet._instance = None
        CDPSovereignWallet._initialized = False
