# This file is part of CORTEX.
# Licensed under the Apache License, Version 2.0.
# See top-level LICENSE file for details.
# Change Date: 2030-01-01 (Transitions to Apache 2.0)

"""AlphaCode — Domain models and configuration.

All data types are immutable where possible. No mutable global state.
Type-hinted exhaustively per Antigravity Standards.
"""

from __future__ import annotations

import hashlib
import time
from dataclasses import dataclass, field
from enum import Enum

from pydantic import BaseModel, Field

# ─── Enums ───────────────────────────────────────────────────────────────


class Language(str, Enum):
    """Supported programming languages for solution generation."""

    PYTHON = "python"
    CPP = "cpp"
    JAVASCRIPT = "javascript"


class SolutionStatus(str, Enum):
    """Status of a solution through the pipeline stages."""

    SAMPLED = "sampled"
    PASSED = "passed"
    FAILED = "failed"
    TIMEOUT = "timeout"
    COMPILE_ERROR = "compile_error"
    RUNTIME_ERROR = "runtime_error"
    CLUSTERED = "clustered"
    SCORED = "scored"
    SELECTED = "selected"


# ─── Problem Definition ─────────────────────────────────────────────────


class TestCase(BaseModel):
    """A single input/output test case for a competitive programming problem."""

    input: str = Field(description="Test input (fed to stdin)")
    expected_output: str = Field(description="Expected output (compared to stdout)")

    model_config = {"frozen": True}


class Problem(BaseModel):
    """A competitive programming problem specification.

    Follows Codeforces-style problem format:
    - Statement with constraints
    - Example test cases (public)
    - Optional hidden test cases for validation
    """

    title: str = Field(description="Problem title")
    statement: str = Field(description="Full problem statement with constraints")
    example_tests: list[TestCase] = Field(
        min_length=1,
        description="Public example test cases (used for filtering)",
    )
    hidden_tests: list[TestCase] = Field(
        default_factory=list,
        description="Hidden test cases (used for final validation only)",
    )
    time_limit_seconds: float = Field(default=2.0, gt=0)
    memory_limit_mb: int = Field(default=256, gt=0)
    language: Language = Field(default=Language.PYTHON)
    tags: list[str] = Field(default_factory=list)
    difficulty_rating: int | None = Field(
        default=None, ge=800, le=3500, description="Codeforces-style rating"
    )
    source_url: str | None = Field(default=None)

    model_config = {"frozen": True}


# ─── Pipeline Data Models ────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class SampledSolution:
    """A raw solution generated by the LLM sampler."""

    code: str
    sample_index: int
    temperature: float
    model_name: str
    generation_time_ms: float
    timestamp: float = field(default_factory=time.time)

    @property
    def code_hash(self) -> str:
        """Deterministic content hash for deduplication."""
        return hashlib.sha256(self.code.strip().encode()).hexdigest()[:16]


@dataclass(frozen=True, slots=True)
class TestResult:
    """Result of running a solution against a single test case."""

    test_index: int
    passed: bool
    actual_output: str
    expected_output: str
    execution_time_ms: float
    error: str | None = None


@dataclass(frozen=True, slots=True)
class FilteredSolution:
    """A solution that survived the filtering stage."""

    code: str
    code_hash: str
    sample_index: int
    status: SolutionStatus
    test_results: tuple[TestResult, ...]
    pass_rate: float  # 0.0 to 1.0

    @property
    def passed_all(self) -> bool:
        return self.pass_rate == 1.0


@dataclass(frozen=True, slots=True)
class OutputSignature:
    """Deterministic output fingerprint for clustering.

    Solutions that produce identical outputs on the same generated
    test inputs are considered semantically equivalent.
    """

    signature_hash: str
    outputs: tuple[str, ...]

    @staticmethod
    def from_outputs(outputs: list[str]) -> OutputSignature:
        """Create signature from a list of outputs."""
        canonical = tuple(o.strip() for o in outputs)
        sig = hashlib.sha256("|".join(canonical).encode()).hexdigest()[:24]
        return OutputSignature(signature_hash=sig, outputs=canonical)


@dataclass(frozen=True, slots=True)
class ClusterResult:
    """A cluster of semantically equivalent solutions."""

    cluster_id: int
    signature: OutputSignature
    solutions: tuple[FilteredSolution, ...]
    cardinality: int  # len(solutions)
    representative: FilteredSolution  # best solution in cluster

    @property
    def confidence(self) -> float:
        """Higher cardinality → higher confidence that this cluster is correct."""
        return min(self.cardinality / 10.0, 1.0)


@dataclass(frozen=True, slots=True)
class ScoredSolution:
    """A solution with an LLM-assigned correctness score."""

    solution: FilteredSolution
    cluster_id: int
    score: float  # 0.0 to 1.0
    scoring_model: str
    rationale: str | None = None


@dataclass(frozen=True, slots=True)
class SubmissionSet:
    """Final set of diverse solutions ready for submission."""

    problem_title: str
    solutions: tuple[ScoredSolution, ...]
    total_sampled: int
    total_passed_filter: int
    total_clusters: int
    pipeline_duration_ms: float

    @property
    def best(self) -> ScoredSolution | None:
        """Highest-scored solution."""
        if not self.solutions:
            return None
        return max(self.solutions, key=lambda s: s.score)


# ─── Configuration ───────────────────────────────────────────────────────


class AlphaCodeConfig(BaseModel):
    """Configuration for the AlphaCode pipeline.

    Follows DeepMind's architecture with practical defaults
    for local/cloud execution.
    """

    # Sampling
    num_samples: int = Field(
        default=50,
        ge=1,
        le=10_000,
        description="Number of candidate solutions to generate",
    )
    temperature_range: tuple[float, float] = Field(
        default=(0.6, 1.2),
        description="Temperature range for diverse sampling (min, max)",
    )
    max_tokens_per_sample: int = Field(default=4096, gt=0)

    # Filtering
    execution_timeout_seconds: float = Field(
        default=10.0, gt=0, description="Per-test-case execution timeout"
    )
    require_all_examples_pass: bool = Field(
        default=True,
        description="If True, discard solutions that fail any example test",
    )

    # Clustering
    num_generated_inputs: int = Field(
        default=20,
        ge=1,
        le=200,
        description="Number of synthetic test inputs to generate for clustering",
    )
    max_clusters: int = Field(
        default=10,
        ge=1,
        le=100,
        description="Maximum number of clusters to retain",
    )

    # Scoring
    use_llm_scoring: bool = Field(
        default=True,
        description="Use LLM to score solutions within clusters",
    )
    scoring_temperature: float = Field(default=0.1, ge=0.0, le=2.0)

    # Submission
    max_submissions: int = Field(
        default=10,
        ge=1,
        le=50,
        description="Maximum number of solutions to submit",
    )

    # Concurrency
    max_concurrent_samples: int = Field(
        default=10,
        ge=1,
        le=100,
        description="Max parallel LLM requests during sampling",
    )
    max_concurrent_executions: int = Field(
        default=20,
        ge=1,
        le=100,
        description="Max parallel sandbox executions during filtering",
    )

    model_config = {"frozen": True}

    def temperature_for_sample(self, index: int) -> float:
        """Deterministic temperature schedule across samples.

        Linearly interpolates between min and max temperature,
        ensuring diversity across the sample population.
        """
        if self.num_samples <= 1:
            return self.temperature_range[0]
        t = index / (self.num_samples - 1)
        lo, hi = self.temperature_range
        return lo + t * (hi - lo)
