from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Render a Markdown evidence pack from a PostgreSQL smoke JSON report."
    )
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Path to the JSON report generated by postgres_primary_smoke.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Optional Markdown path to write. Defaults to the input path with .md suffix.",
    )
    return parser


def build_markdown_report(report: dict[str, Any]) -> str:
    checkpoint = report.get("checkpoint", {}).get("payload", {})
    ledger = report.get("ledger", {}).get("payload", {})
    vote = report.get("vote", {}).get("payload", {})
    store = report.get("store", {}).get("payload", {})
    search = report.get("search", {}).get("payload", [])

    top_search_id = "n/a"
    if isinstance(search, list) and search:
        top_search_id = str(search[0].get("fact_id", "n/a"))

    lines = [
        "# PostgreSQL Vertical Smoke Evidence",
        "",
        f"- Timestamp: `{report.get('timestamp', 'unknown')}`",
        f"- Target: `{report.get('target', 'unknown')}`",
        f"- Tenant: `{report.get('tenant_id', 'unknown')}`",
        f"- Project: `{report.get('project', 'unknown')}`",
        f"- Result: `{'PASS' if report.get('passed') else 'FAIL'}`",
        "",
        "## Executed Path",
        "",
        "`store -> search -> vote -> checkpoint -> ledger/status`",
        "",
        "## Assertions",
        "",
        f"- Stored fact id: `{store.get('id', 'n/a')}`",
        f"- Vote recorded: `{vote.get('vote', 'n/a')}`",
        f"- Top search fact id: `{top_search_id}`",
        f"- Transaction checkpoint id: `{checkpoint.get('checkpoint_id', 'n/a')}`",
        f"- Vote checkpoint id: `{checkpoint.get('vote_checkpoint_id', 'n/a')}`",
        f"- Ledger valid: `{ledger.get('valid', False)}`",
        f"- Transactions checked: `{ledger.get('tx_checked', 0)}`",
        f"- Roots checked: `{ledger.get('roots_checked', 0)}`",
        f"- Votes checked: `{ledger.get('votes_checked', 0)}`",
        f"- Vote checkpoints checked: `{ledger.get('vote_checkpoints_checked', 0)}`",
        "",
    ]

    violations = ledger.get("violations", [])
    if violations:
        lines.extend(
            [
                "## Violations",
                "",
                "```json",
                json.dumps(violations, indent=2, ensure_ascii=False),
                "```",
                "",
            ]
        )

    return "\n".join(lines)


def main() -> int:
    args = build_parser().parse_args()
    report = json.loads(args.input.read_text(encoding="utf-8"))
    markdown = build_markdown_report(report)
    output_path = args.output or args.input.with_suffix(".md")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown, encoding="utf-8")
    print(markdown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
