#!/usr/bin/env python3
"""
Adversarial Test Suite for CORTEX Merkle Infrastructure.

Tests tamper-evidence guarantees under hostile conditions:
1. Proof verification (positive + negative)
2. Event mutation detection
3. Event reordering detection
4. Manifest signature falsification
5. MMR state persistence and restoration
6. Scale test (10K events)

Run: PYTHONPATH=. python3 scratch/test_merkle_adversarial.py
"""

import hashlib
import sqlite3
import sys
import time
from decimal import Decimal

# Register Decimal adapter before any CORTEX imports
sqlite3.register_adapter(Decimal, lambda d: str(d))
sqlite3.register_converter("DECIMAL", lambda s: Decimal(s.decode("ascii")))

from cortex.crypto.keys import ZKSwarmIdentity
from cortex.crypto.merkle import (
    AppendOnlyMerkleTree,
    EvidenceManifest,
    MerkleProof,
    MerkleTree,
    MMRState,
)

PASS = "✅"
FAIL = "❌"
results: list[tuple[str, bool, str]] = []


def report(name: str, passed: bool, detail: str = "") -> None:
    results.append((name, passed, detail))
    icon = PASS if passed else FAIL
    suffix = f" — {detail}" if detail else ""
    print(f"  {icon} {name}{suffix}")


# ─── Test 1: Proof self-verification ────────────────────────────


def test_proof_self_verification() -> None:
    """Every proof generated by the tree must self-verify."""
    print("\n[1] Proof Self-Verification")
    tree = MerkleTree(algorithm="sha256")
    events = [f"event_{i}" for i in range(8)]
    tree.add_events(events)
    tree.build()

    for i in range(len(events)):
        proof = tree.get_proof(i)
        ok = proof.verify()
        report(f"Proof[{i}] self-verify", ok)


# ─── Test 2: Tampered leaf detection ────────────────────────────


def test_tampered_leaf_detection() -> None:
    """A modified leaf hash must fail proof verification."""
    print("\n[2] Tampered Leaf Detection")
    tree = MerkleTree(algorithm="sha256")
    tree.add_events(["alpha", "beta", "gamma", "delta"])
    tree.build()

    proof = tree.get_proof(1)

    # Forge a different leaf hash
    forged = MerkleProof(
        leaf_hash=hashlib.sha256(b"FORGED").hexdigest(),
        leaf_index=proof.leaf_index,
        siblings=proof.siblings,
        directions=proof.directions,
        root=proof.root,
        tree_size=proof.tree_size,
        algorithm=proof.algorithm,
    )
    ok = not forged.verify()
    report("Forged leaf rejected", ok)


# ─── Test 3: Event reordering detection ─────────────────────────


def test_event_reordering() -> None:
    """Swapping event order must produce a different root."""
    print("\n[3] Event Reordering Detection")
    events_a = ["first", "second", "third"]
    events_b = ["second", "first", "third"]

    tree_a = MerkleTree()
    tree_a.add_events(events_a)
    root_a = tree_a.build()

    tree_b = MerkleTree()
    tree_b.add_events(events_b)
    root_b = tree_b.build()

    ok = root_a != root_b
    report("Reordered events produce different root", ok, f"{root_a[:16]}… ≠ {root_b[:16]}…")


# ─── Test 4: Manifest signature verification ────────────────────


def test_manifest_signature() -> None:
    """Manifest with valid Ed25519 signature must verify."""
    print("\n[4] Manifest Signature Verification")

    tree = MerkleTree(algorithm="sha256")
    tree.add_events(["tx_001", "tx_002", "tx_003"])
    tree.build()

    keypair = ZKSwarmIdentity.generate_keypair()
    root = tree.get_root() or ""
    signature = ZKSwarmIdentity.sign_payload(root, keypair.private_key_b64)

    manifest = tree.create_manifest(
        signer_did=keypair.public_key_b64,
        signature=signature,
        period=("2026-01-01", "2026-05-09"),
    )

    # Valid verification
    ok = EvidenceManifest.verify_manifest(manifest)
    report("Valid manifest verifies", ok)

    # Tamper with signature
    manifest_dict = manifest.to_dict()
    manifest_dict["signature"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
    ok2 = not EvidenceManifest.verify_manifest(manifest_dict)
    report("Forged signature rejected", ok2)

    # Tamper with root
    manifest_dict2 = manifest.to_dict()
    manifest_dict2["merkle_root"] = "0" * 64
    ok3 = not EvidenceManifest.verify_manifest(manifest_dict2)
    report("Tampered root rejected", ok3)


# ─── Test 5: Manifest serialization roundtrip ───────────────────


def test_manifest_roundtrip() -> None:
    """Manifest must survive to_dict() → from_dict() roundtrip."""
    print("\n[5] Manifest Serialization Roundtrip")

    tree = MerkleTree()
    tree.add_events(["a", "b", "c", "d"])
    tree.build()

    keypair = ZKSwarmIdentity.generate_keypair()
    root = tree.get_root() or ""
    sig = ZKSwarmIdentity.sign_payload(root, keypair.private_key_b64)

    original = tree.create_manifest(
        signer_did=keypair.public_key_b64,
        signature=sig,
    )

    serialized = original.to_dict()
    restored = EvidenceManifest.from_dict(serialized)

    ok = restored.merkle_root == original.merkle_root
    report("Root preserved", ok)
    ok2 = restored.total_events == original.total_events
    report("Event count preserved", ok2)
    ok3 = restored.signature == original.signature
    report("Signature preserved", ok3)
    ok4 = EvidenceManifest.verify_manifest(restored)
    report("Restored manifest verifies", ok4)


# ─── Test 6: MMR state persistence ──────────────────────────────


def test_mmr_state_persistence() -> None:
    """MMR must produce identical roots after state export/restore."""
    print("\n[6] MMR State Persistence")

    mmr = AppendOnlyMerkleTree(algorithm="sha3_256")
    for i in range(100):
        mmr.add_event(f"event_{i}")

    root_before = mmr.get_root()
    state = mmr.export_state()
    state_dict = state.to_dict()

    # Simulate restoring on a different machine
    mmr2 = AppendOnlyMerkleTree()
    mmr2.restore_state(MMRState.from_dict(state_dict))

    root_after = mmr2.get_root()
    ok = root_before == root_after
    report("Root matches after restore", ok)

    # Add more events to both and verify they diverge correctly
    mmr.add_event("extra_a")
    mmr2.add_event("extra_a")
    ok2 = mmr.get_root() == mmr2.get_root()
    report("Parallel append produces same root", ok2)


# ─── Test 7: MMR incremental consistency ────────────────────────


def test_mmr_incremental_consistency() -> None:
    """MMR root must change with every append."""
    print("\n[7] MMR Incremental Consistency")

    mmr = AppendOnlyMerkleTree()
    roots: list[str] = []
    for i in range(16):
        root = mmr.add_event(f"event_{i}")
        roots.append(root)

    unique_roots = set(roots)
    ok = len(unique_roots) == len(roots)
    report(
        "All 16 roots unique",
        ok,
        f"{len(unique_roots)}/{len(roots)} unique",
    )


# ─── Test 8: Scale benchmark (10K events) ───────────────────────


def test_scale_10k() -> None:
    """Benchmark: 10K events in MMR."""
    print("\n[8] Scale Benchmark (10K events)")

    mmr = AppendOnlyMerkleTree()
    t0 = time.perf_counter()
    for i in range(10_000):
        mmr.add_event(f"high_volume_event_{i:06d}")
    t1 = time.perf_counter()

    elapsed_ms = (t1 - t0) * 1000
    events_per_sec = 10_000 / (t1 - t0)

    ok = elapsed_ms < 5000  # Must complete in < 5s
    report(
        "10K events appended",
        ok,
        f"{elapsed_ms:.1f}ms ({events_per_sec:.0f} evt/s)",
    )

    root = mmr.get_root()
    ok2 = len(root) == 64  # SHA-256 hex
    report("Root valid", ok2, root[:16] + "…")


# ─── Test 9: SHA3-256 parity ────────────────────────────────────


def test_sha3_parity() -> None:
    """SHA3-256 tree must produce different roots from SHA-256."""
    print("\n[9] SHA3-256 / SHA-256 Parity")

    events = ["sovereign", "audit", "trail"]

    tree_256 = MerkleTree(algorithm="sha256")
    tree_256.add_events(events)
    root_256 = tree_256.build()

    tree_3 = MerkleTree(algorithm="sha3_256")
    tree_3.add_events(events)
    root_3 = tree_3.build()

    ok = root_256 != root_3
    report("SHA-256 ≠ SHA3-256 roots", ok)

    # But each must be internally consistent
    proof_256 = tree_256.get_proof(0)
    proof_3 = tree_3.get_proof(0)
    ok2 = proof_256.verify() and proof_3.verify()
    report("Both proofs self-verify", ok2)


# ─── Test 10: Empty tree edge cases ─────────────────────────────


def test_empty_tree_edges() -> None:
    """Empty trees must not crash or produce invalid manifests."""
    print("\n[10] Empty Tree Edge Cases")

    tree = MerkleTree()
    root = tree.get_root()
    ok = root == "" or root is None
    report("Empty tree root is empty/None", ok)

    try:
        tree.create_manifest()
        report("Empty manifest raises", False, "Should have raised")
    except ValueError:
        report("Empty manifest raises ValueError", True)

    mmr = AppendOnlyMerkleTree()
    ok2 = mmr.get_root() == ""
    report("Empty MMR root is empty", ok2)


# ─── Main ────────────────────────────────────────────────────────


def main() -> int:
    print("=" * 60)
    print("  CORTEX Merkle Adversarial Test Suite")
    print("  EU AI Act Article 12 — Tamper-Evidence Validation")
    print("=" * 60)

    test_proof_self_verification()
    test_tampered_leaf_detection()
    test_event_reordering()
    test_manifest_signature()
    test_manifest_roundtrip()
    test_mmr_state_persistence()
    test_mmr_incremental_consistency()
    test_scale_10k()
    test_sha3_parity()
    test_empty_tree_edges()

    # Summary
    passed = sum(1 for _, ok, _ in results if ok)
    total = len(results)
    failed = total - passed

    print("\n" + "=" * 60)
    if failed == 0:
        print(f"  {PASS} ALL {total} TESTS PASSED — Tamper-evidence verified.")
    else:
        print(f"  {FAIL} {failed}/{total} TESTS FAILED")
        for name, ok, detail in results:
            if not ok:
                print(f"    → {name}: {detail}")
    print("=" * 60)

    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
